### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Kuzirashi** [ember-cli/ember-cli-inject-live-reload#34]
Hey, 100% Ember apps depend on this addon however there aren't any tests in this repo. Now @wongpeiyi opened issue because he's uncertain how something should work and I understand him. I think there should be tests created for this. It would be probably possible to setup Mocha tests + Travis CI on this. What do you think?

**Comment by rwjblue** [comment]
Tests would be great! I would definitely welcome PR's and am happy to setup Travis.

**Comment by rwjblue** [comment]
Now that master is fixed (thank you again for all the research in #35), would you still be interested in some tests?

**Comment by Turbo87** [comment]
closing this issue as we seem to have tests and they also run on TravisCI now
