### ISSUE TITLE
Possibility of having different server port and base url port

### ISSUE THREAD

**Issue by swapnilsm** [ember-cli/ember-cli-inject-live-reload#46]
With introduction of deployment technologies like Kubernetes and ECS, the services need to have an internal port on which they listen and an external port which is mapped to the internal port. This introduces the need of having a way to specify the internal port on which the server needs to be started and one more port to which the script will try to access from the browser. 
So there should be possible configuration option to specify an extra port if the deployment is made through K8S or ECS.

**Comment by swapnilsm** [comment]
@rwjblue I can take this up.

**Comment by rwjblue** [comment]
Sorry for the delayed reply here, I believe that this is taken care of by https://github.com/ember-cli/ember-cli-inject-live-reload/pull/113.
