### ISSUE TITLE
Incorrect dynamic script returned when hostname and ember server are on different ports. Setting `options.liveReloadPort` breaks the loading of livereload.js script

### ISSUE THREAD

**Issue by sumeetattree** [ember-cli/ember-cli-inject-live-reload#56]
Background:
Ember server running on `192.168.0.244:4200`
Rails server that serves the built app is running on `192.168.0.244:3000`
We are following the `ember-cli-deploy` lightning method which pushes the built html file to redis store which is then served via rails.

There are two things that are going on here:
1. if you set `liveReloadPort: 4200`, nothing happens. livereload.js is still served from `192.168.0.244:3000`. I suspect it is due to these lines [here](https://github.com/ember-cli/ember-cli-inject-live-reload/blob/68c237eca6cefc760a97ab30f37c215c84bd7fc7/index.js#L25)
```js
    if (options.liveReloadPort !== options.port) {
      liveReloadPort = options.liveReloadPort
    }
```
If they are same, which they are in this case, `liveReloadPort` never gets set. Which would be fine if the script was actually loaded from `4200` but it looks at the `location.port` which is `3000`

2. If you set `liveReloadPort: 4700` (some arbitrary number), the generated dynamic script breaks on [this line](https://github.com/ember-cli/ember-cli-inject-live-reload/blob/68c237eca6cefc760a97ab30f37c215c84bd7fc7/index.js#L34) with this error:
```js
    var prefixURL = '(location.protocol || 'http:') + '//' + host + ':' + 4700'; // Syntax Error
```

Unrelated; could I also interest you in exposing `liveReloadBaseUrl, liveReloadPort, and liveReloadHost` via ember-cli-build config? Currently we are serving these files from a different port (4200) than the server that's serving the files (3000). Something like this would be ideal:
```js
    // ember-cli-build.js
    let app = new EmberApp(defaults, {
      emberCLILiveReload: {
        liveReloadBaseUrl: process.env.ASSET_HOST,
        liveReloadPort: 4700
      },
    });
```
These options can then be merged like so on this [line](https://github.com/ember-cli/ember-cli-inject-live-reload/blob/68c237eca6cefc760a97ab30f37c215c84bd7fc7/index.js#L46)
```js
  serverMiddleware: function(config) {
    var self = this;
    var app = config.app;
    var options = config.options;
    // this will become
    var options = Object.assign(config.options, this.app.options.emberCLILiveReload)
```

**Comment by Paxxinet** [comment]
> 1. If you set `liveReloadPort: 4700` (some arbitrary number), the generated dynamic script breaks on [this line](https://github.com/ember-cli/ember-cli-inject-live-reload/blob/68c237eca6cefc760a97ab30f37c215c84bd7fc7/index.js#L34) with this error:
> 
> ```js
>     var prefixURL = '(location.protocol || 'http:') + '//' + host + ':' + 4700'; // Syntax Error
> ```

Even when no changes are made to a brand new project (ember version 2.18.0), this error is shown:

![error with 2_0_0 version 1](https://user-images.githubusercontent.com/2405752/46953056-5cc63c00-d095-11e8-9c3a-aaf02fe8d729.png)
![error with 2_0_0 version 2](https://user-images.githubusercontent.com/2405752/46953057-5cc63c00-d095-11e8-9f1a-1315ecb8312f.png)

**Comment by rwjblue** [comment]
Thank you for such a detailed issue report!

**Comment by rwjblue** [comment]
Also requires https://github.com/ember-cli/ember-cli-inject-live-reload/pull/66 to work with ember-cli@3.5.0...
