### ISSUE TITLE
>= 1.10 Doesn't Respect `liveReloadBaseUrl`

### ISSUE THREAD

**Issue by jherdman** [ember-cli/ember-cli-inject-live-reload#68]
Ember: 3.5.0

Our apps are delivered in development mode via Nginx at a URL something like this:

http://example.com/some-app
http://example.com/another-app

some-app is, for instance, really found on http://example.com:4206/some-app.

Prior to v1.10+ we could get away with configuring LR as follows in our .ember-cli file:

```
"liveReloadBaseUrl": "http://example.com:4206/"
```

In the current versions I can't seem to get the right series of incantations to get this to work any more.

Here's what I've tried:

Host/Port Combo
------------------

```
"liveReloadHost": "http://example.com",
"liveReloadPort": "4206"
```

* cannot find ember-cli-live-reload.js at http://example.com/ember-cli-live-reload.js (it's missing the port)

Host/Port/ENV VAR
--------------------

https://github.com/ember-cli/ember-cli-inject-live-reload/blob/09f152591138c18388eb7832835f675ec289d8ad/index.js#L9-L16 seems to imply I can pass an env var, so above with `export EMBER_CLI_INJECT_LIVE_RELOAD_BASEURL="http://example.com:4206"

Same error.

More Advanced Vars
---------------------

```
"liveReloadOptions": {
  "host": "example.com",
  "port": 4206
}
```

Same error

JS URL
-------

```
"liveReloadJsUrl": "http://example.com:4206/_lr/livereload.js"
```

Same error.

Workaround
------

The work around right now is to downgrade and pin to 1.8.2. I assume the problem is something to do with the middleware configuration for modern Ember.

**Comment by rwjblue** [comment]
thank you for the awesome write up, would you mind adding another scenario to our tests!

Something like this one:

https://github.com/ember-cli/ember-cli-inject-live-reload/blob/6177d46bf3d7aa7e1da5e7c0b9d755282e63336d/tests/inject-live-reload-test.js#L90-L96

But with the options that you were using? Presumably it fails now (due to not incorporating the port) but having the test helps us 1) make sure we don’t regress in the future, 2) that I actually understand the problem properly 😜

**Comment by jherdman** [comment]
PR opened! It looks like I was affected by the Github outage.

**Comment by rwjblue** [comment]
I think this was fixed in https://github.com/ember-cli/ember-cli-inject-live-reload/pull/113 (please double check).

**Comment by jherdman** [comment]
Worked like a charm!

**Comment by rwjblue** [comment]
Thanks for confirming!
